"""Synthetic smoke fixtures. These are MOCK_ONLY and never evidence."""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw

from certvic.hashing import sha256_file, stable_record_hash
from certvic.schema import (
    AnswerFormat,
    Domain,
    EditSpec,
    EditType,
    LicenseCategory,
    MaskRecord,
    RequiredChange,
    SCHEMA_VERSION,
    SourceImageRecord,
    TaskFamily,
    TaskItem,
)


def _draw_pair(path_original: Path, path_variant: Path, path_mask: Path, family: str, seed: int) -> None:
    size = (64, 64)
    base = Image.new("RGB", size, (238, 238, 232))
    edited = base.copy()
    mask = Image.new("L", size, 0)
    draw = ImageDraw.Draw(base)
    edit_draw = ImageDraw.Draw(edited)
    mask_draw = ImageDraw.Draw(mask)

    x = 18 + (seed % 5)
    if family == TaskFamily.SUPPORT_STABILITY.value:
        draw.rectangle([20, 44, 46, 50], fill=(90, 90, 90))
        draw.rectangle([x, 24, x + 20, 42], fill=(80, 140, 220))
        edit_draw.rectangle([x, 24, x + 20, 42], fill=(80, 140, 220))
        mask_draw.rectangle([20, 44, 46, 50], fill=255)
    elif family == TaskFamily.AFFORDANCE_REACHABILITY.value:
        draw.ellipse([12, 24, 24, 38], fill=(180, 120, 80))
        draw.rectangle([28, 26, 42, 34], fill=(60, 150, 80))
        edit_draw.ellipse([12, 24, 24, 38], fill=(180, 120, 80))
        edit_draw.rectangle([48, 26, 60, 34], fill=(60, 150, 80))
        mask_draw.rectangle([28, 26, 42, 34], fill=255)
    elif family == TaskFamily.OCCLUSION_SAFETY.value:
        draw.rectangle([28, 20, 42, 42], fill=(190, 50, 50))
        edit_draw.rectangle([28, 20, 42, 42], fill=(110, 110, 110))
        mask_draw.rectangle([28, 20, 42, 42], fill=255)
    else:
        draw.rectangle([20, 20, 40, 40], fill=(70, 170, 120))
        edit_draw.rectangle([2, 2, 14, 14], fill=(180, 180, 240))
        mask_draw.rectangle([20, 20, 40, 40], fill=255)

    path_original.parent.mkdir(parents=True, exist_ok=True)
    path_variant.parent.mkdir(parents=True, exist_ok=True)
    path_mask.parent.mkdir(parents=True, exist_ok=True)
    base.save(path_original)
    edited.save(path_variant)
    mask.save(path_mask)


def generate_smoke_tasks(root_dir: str | Path = "data/smoke", n_items: int = 12) -> list[TaskItem]:
    root = Path(root_dir)
    image_dir = root / "images"
    mask_dir = root / "masks"
    families = [
        TaskFamily.SUPPORT_STABILITY.value,
        TaskFamily.AFFORDANCE_REACHABILITY.value,
        TaskFamily.CONTROL_IRRELEVANT.value,
        TaskFamily.OCCLUSION_SAFETY.value,
    ]
    tasks: list[TaskItem] = []
    for idx in range(n_items):
        family = families[idx % len(families)]
        item_id = f"smoke_{idx:03d}"
        original_path = image_dir / f"{item_id}_orig.png"
        variant_path = image_dir / f"{item_id}_var.png"
        mask_path = mask_dir / f"{item_id}_mask.png"
        _draw_pair(original_path, variant_path, mask_path, family, idx)

        if family == TaskFamily.SUPPORT_STABILITY.value:
            edit_type = EditType.REMOVE.value
            answer_original, answer_edited, required = "yes", "no", RequiredChange.CHANGE.value
            question = "Is the upper object physically supported? Respond with exactly one token: yes or no."
        elif family == TaskFamily.AFFORDANCE_REACHABILITY.value:
            edit_type = EditType.DISPLACE.value
            answer_original, answer_edited, required = "yes", "no", RequiredChange.CHANGE.value
            question = "Can the person use the target object immediately without moving closer? Respond with exactly one token: yes or no."
        elif family == TaskFamily.OCCLUSION_SAFETY.value:
            edit_type = EditType.OCCLUDE.value
            answer_original, answer_edited, required = "no", "no", RequiredChange.NO_CHANGE.value
            question = "Should the agent proceed immediately based only on the visible scene? Respond with exactly one token: yes or no."
        else:
            edit_type = EditType.CONTROL_COLOR.value
            answer_original, answer_edited, required = "yes", "yes", RequiredChange.NO_CHANGE.value
            question = "Is the target object visible in the scene? Respond with exactly one token: yes or no."

        source = SourceImageRecord(
            source_id=f"source_{item_id}",
            source_name="certvic synthetic smoke fixture",
            source_url_or_pointer=None,
            local_path=str(original_path),
            sha256=sha256_file(original_path),
            license_category=LicenseCategory.CC0.value,
            license_text="Synthetic fixture generated by CertVIC smoke builder.",
            redistribution_allowed=True,
            notes="MOCK_ONLY synthetic fixture; not evidence.",
        )
        mask = MaskRecord(
            mask_id=f"mask_{item_id}",
            source_id=source.source_id,
            mask_path=str(mask_path),
            object_label="synthetic_target",
            bbox_xyxy=[12, 20, 60, 50],
            mask_sha256=sha256_file(mask_path),
            method="synthetic_smoke",
            quality_notes="MOCK_ONLY",
        )
        edit = EditSpec(
            edit_id=f"edit_{item_id}",
            source_id=source.source_id,
            mask_id=mask.mask_id,
            edit_type=edit_type,
            task_family=family,
            domain=Domain.SYNTHETIC_SANITY.value,
            seed=idx,
            params={"smoke": True},
            expected_effect=f"synthetic {family} fixture",
            single_factor=True,
            edited_image_path=str(variant_path),
            edited_sha256=sha256_file(variant_path),
        )
        metadata = {
            "evidence_status": "MOCK_ONLY",
            "task_hash": "",
            "source_hash": stable_record_hash(source),
            "edit_hash": stable_record_hash(edit),
            "schema_version": SCHEMA_VERSION,
        }
        task = TaskItem(
            item_id=item_id,
            source=source,
            mask=mask,
            edit=edit,
            original_image_path=str(original_path),
            edited_image_path=str(variant_path),
            question_original=question,
            question_edited=question,
            answer_original=answer_original,
            answer_edited=answer_edited,
            required_change=required,
            answer_format=AnswerFormat.YES_NO.value,
            task_family=family,
            domain=Domain.SYNTHETIC_SANITY.value,
            split="smoke",
            metadata=metadata,
        )
        dumped = task.model_dump(mode="json")
        dumped["metadata"]["task_hash"] = stable_record_hash({k: v for k, v in dumped.items() if k != "metadata"})
        tasks.append(TaskItem.model_validate(dumped))
    return tasks
