"""Build the CertVIC V8 post-newruns artifact set.

CPU-only. This script ingests already-downloaded Kaggle outputs from
``kaggleoutputs/newruns`` and builds reproducibility reports. It does not run
models, does not fabricate predictions, and keeps all evidence flags pilot-only
or diagnostic-only.
"""

from __future__ import annotations

import csv
import hashlib
import json
import shutil
import subprocess
import sys
import zipfile
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from certvic.io import read_jsonl, write_json  # noqa: E402
from certvic.v8.mechanism_probe_report import build as build_mechanism_report  # noqa: E402
from certvic.v8.polarity_ablation_report import build as build_polarity_report  # noqa: E402

REPO = Path(__file__).resolve().parents[1]
NEWRUNS = REPO / "kaggleoutputs/newruns"
RESULTS = REPO / "data/results/main_real_200"
V8 = RESULTS / "v8_upgrade"
STAGING = V8 / "staging"
REPORTS = V8 / "reports"
TABLES = V8 / "tables"
FIGURES = V8 / "figures"

PROVIDERS = ("qwen2_5_vl_7b", "internvl_8b", "llava_onevision_7b")
MODEL_NAMES = {
    "qwen2_5_vl_7b": "Qwen/Qwen2.5-VL-7B-Instruct",
    "internvl_8b": "OpenGVLab/InternVL2-8B",
    "llava_onevision_7b": "llava-hf/llava-onevision-qwen2-7b-ov-hf",
}
RUNS = {
    "spurious": {
        "expected_rows": 188,
        "dest_dir": RESULTS / "kaggle_spurious",
        "filename": "pred_{provider}_spurious_merged.jsonl",
        "zip": "{provider}_spurious_preds.zip",
    },
    "perception_scaled": {
        "expected_rows": 738,
        "dest_dir": RESULTS / "kaggle_perception_scaled",
        "filename": "pred_{provider}_perception_scaled_merged.jsonl",
        "zip": "{provider}_perception_scaled_preds.zip",
    },
    "polarity": {
        "expected_rows": 728,
        "dest_dir": RESULTS / "kaggle_polarity",
        "filename": "pred_{provider}_polarity.jsonl",
        "zip": "{provider}_polarity_preds.zip",
    },
    "mechanism": {
        "expected_rows": 364,
        "dest_dir": RESULTS / "kaggle_mechanism",
        "filename": "pred_{provider}_mechanism.jsonl",
        "zip": "{provider}_mechanism_preds.zip",
    },
}
SPURIOUS_THRESHOLD = 0.10


def _rel(path: Path) -> str:
    try:
        return path.relative_to(REPO).as_posix()
    except ValueError:
        return str(path)


def _sha256_bytes(data: bytes) -> str:
    h = hashlib.sha256()
    h.update(data)
    return h.hexdigest()


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _read_jsonl_bytes(data: bytes) -> list[dict]:
    return [json.loads(line) for line in data.decode("utf-8").splitlines() if line.strip()]


def _read_jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def _write_jsonl(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, sort_keys=True) + "\n")


def _copy_if_missing_or_identical(src: Path, dest: Path) -> tuple[str, str | None]:
    dest.parent.mkdir(parents=True, exist_ok=True)
    src_hash = _sha256_file(src)
    if dest.exists():
        dest_hash = _sha256_file(dest)
        if dest_hash == src_hash:
            return "already_identical", None
        return "blocked_conflict", f"{_rel(dest)} exists with different sha256"
    shutil.copy2(src, dest)
    return "copied", None


def setup_dirs() -> None:
    for d in (V8, STAGING, REPORTS, TABLES, FIGURES):
        d.mkdir(parents=True, exist_ok=True)


def write_contract() -> None:
    _write_text(
        V8 / "V8_NONFABRICATION_CONTRACT.md",
        "\n".join([
            "# V8 Non-Fabrication Contract",
            "",
            "- No model predictions are generated by this local builder.",
            "- Only real files found under `kaggleoutputs/newruns` may be normalized.",
            "- Missing or malformed artifacts become BLOCKED, not filled in.",
            "- `paper_evidence` remains false for every V8 artifact created here.",
            "- Spurious specificity gates are not weakened; a failed provider blocks scale readiness.",
            "- Human-review and IAA fields remain blank until a real reviewer completes them.",
            "",
        ]),
    )


def snapshot_pre_v8() -> dict:
    snap_root = STAGING / "pre_v8_canonical_snapshots"
    manifest: list[dict] = []
    patterns = [
        "pilot_report*/pilot_result.json",
        "pilot_report*/pilot_result.md",
        "raw_predictions*/provenance.json",
        "tables/main200_*.csv",
        "tables/main200_*.tex",
    ]
    for pattern in patterns:
        for src in sorted(RESULTS.glob(pattern)):
            rel = src.relative_to(RESULTS)
            dest = snap_root / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            if not dest.exists():
                shutil.copy2(src, dest)
            manifest.append({
                "source": _rel(src),
                "snapshot": _rel(dest),
                "sha256": _sha256_file(src),
            })
    out = {
        "schema": "certvic.v8.pre_snapshot.v1",
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "n_files": len(manifest),
        "files": manifest,
    }
    write_json(STAGING / "pre_v8_snapshot_manifest.json", out)
    return out


def inventory_newruns() -> dict:
    files: list[dict] = []
    if not NEWRUNS.exists():
        result = {
            "schema": "certvic.v8.newruns_inventory.v1",
            "status": "blocked",
            "root": _rel(NEWRUNS),
            "missing_root": True,
            "files": [],
        }
        write_json(V8 / "newruns_file_inventory.json", result)
        _write_text(V8 / "NEWRUNS_FILE_INVENTORY.md", "# V8 Newruns File Inventory\n\nBLOCKED: `kaggleoutputs/newruns` is missing.\n")
        return result
    for path in sorted(NEWRUNS.rglob("*")):
        if not path.is_file():
            continue
        entry = {
            "path": _rel(path),
            "size_bytes": path.stat().st_size,
            "sha256": _sha256_file(path),
            "kind": "zip" if path.suffix == ".zip" else path.suffix.lstrip("."),
        }
        if path.suffix == ".zip":
            members = []
            with zipfile.ZipFile(path) as zf:
                for info in sorted(zf.infolist(), key=lambda x: x.filename):
                    if info.is_dir():
                        continue
                    data = zf.read(info.filename)
                    members.append({
                        "name": info.filename,
                        "size_bytes": info.file_size,
                        "sha256": _sha256_bytes(data),
                    })
            entry["members"] = members
        files.append(entry)
    result = {
        "schema": "certvic.v8.newruns_inventory.v1",
        "status": "complete",
        "root": _rel(NEWRUNS),
        "missing_root": False,
        "n_files": len(files),
        "files": files,
    }
    write_json(V8 / "newruns_file_inventory.json", result)
    lines = [
        "# V8 Newruns File Inventory",
        "",
        f"Root: `{_rel(NEWRUNS)}`",
        "",
        "| file | bytes | sha256 | notes |",
        "| --- | ---: | --- | --- |",
    ]
    for f in files:
        note = f"{len(f.get('members', []))} zip members" if f["kind"] == "zip" else ""
        lines.append(f"| `{f['path']}` | {f['size_bytes']} | `{f['sha256']}` | {note} |")
    lines.append("")
    _write_text(V8 / "NEWRUNS_FILE_INVENTORY.md", "\n".join(lines))
    return result


def _validate_rows(rows: list[dict], provider: str, run_tag: str, expected_rows: int) -> dict:
    provider_names = sorted({r.get("provider_name") for r in rows})
    if run_tag in {"spurious", "perception_scaled"}:
        ids = [f"{r.get('item_id')}::{r.get('image_variant')}" for r in rows]
    else:
        ids = [str(r.get("prediction_id") or f"{r.get('item_id')}::{r.get('image_variant')}::{i}") for i, r in enumerate(rows)]
    dupes = sorted(k for k, n in Counter(ids).items() if n > 1)
    parse_values = [r.get("parse_ok") for r in rows]
    return {
        "n_rows": len(rows),
        "expected_rows": expected_rows,
        "row_count_ok": len(rows) == expected_rows,
        "provider_names": provider_names,
        "provider_ok": provider_names == [provider],
        "n_duplicate_ids": len(dupes),
        "duplicate_ids_preview": dupes[:10],
        "parse_ok": sum(1 for v in parse_values if v is True),
        "parse_rate": round(sum(1 for v in parse_values if v is True) / len(rows), 4) if rows else None,
    }


def _candidate_direct(provider: str, run_tag: str) -> Path:
    return NEWRUNS / RUNS[run_tag]["filename"].format(provider=provider)


def _candidate_zip_member(provider: str, run_tag: str) -> tuple[Path, str] | None:
    zpath = NEWRUNS / RUNS[run_tag]["zip"].format(provider=provider)
    member = RUNS[run_tag]["filename"].format(provider=provider)
    if not zpath.exists():
        return None
    with zipfile.ZipFile(zpath) as zf:
        if member in zf.namelist():
            return zpath, member
    return None


def _extract_zip_member(zpath: Path, member: str) -> Path:
    if member.startswith("/") or ".." in Path(member).parts:
        raise SystemExit(f"REFUSED: unsafe zip member path: {member}")
    out = STAGING / "newruns_extracted" / zpath.stem / member
    out.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zpath) as zf:
        data = zf.read(member)
    out.write_bytes(data)
    return out


def normalize_predictions() -> dict:
    manifest: dict[str, dict] = {}
    failures: list[str] = []
    for run_tag, cfg in RUNS.items():
        for provider in PROVIDERS:
            expected_rows = cfg["expected_rows"]
            attempts: list[dict] = []
            chosen: Path | None = None
            chosen_source = ""

            direct = _candidate_direct(provider, run_tag)
            if direct.exists():
                rows = _read_jsonl(direct)
                audit = _validate_rows(rows, provider, run_tag, expected_rows)
                attempts.append({"source": _rel(direct), "source_kind": "direct", **audit})
                if audit["row_count_ok"] and audit["provider_ok"] and audit["n_duplicate_ids"] == 0:
                    chosen = direct
                    chosen_source = "direct"

            if chosen is None:
                zip_candidate = _candidate_zip_member(provider, run_tag)
                if zip_candidate is not None:
                    zpath, member = zip_candidate
                    extracted = _extract_zip_member(zpath, member)
                    rows = _read_jsonl(extracted)
                    audit = _validate_rows(rows, provider, run_tag, expected_rows)
                    attempts.append({
                        "source": f"{_rel(zpath)}::{member}",
                        "extracted_path": _rel(extracted),
                        "source_kind": "zip_member",
                        **audit,
                    })
                    if audit["row_count_ok"] and audit["provider_ok"] and audit["n_duplicate_ids"] == 0:
                        chosen = extracted
                        chosen_source = "zip_member"

            dest = cfg["dest_dir"] / cfg["filename"].format(provider=provider)
            key = f"{provider}__{run_tag}"
            if chosen is None:
                failures.append(f"{key}: no valid complete prediction file")
                manifest[key] = {
                    "provider": provider,
                    "run_tag": run_tag,
                    "status": "blocked",
                    "destination": _rel(dest),
                    "attempts": attempts,
                }
                continue
            copy_status, err = _copy_if_missing_or_identical(chosen, dest)
            if err:
                failures.append(f"{key}: {err}")
            rows = _read_jsonl(chosen)
            manifest[key] = {
                "provider": provider,
                "run_tag": run_tag,
                "status": "complete" if not err else "blocked",
                "source": _rel(chosen),
                "source_kind": chosen_source,
                "destination": _rel(dest),
                "copy_status": copy_status,
                "sha256": _sha256_file(chosen),
                "attempts": attempts,
                "validation": _validate_rows(rows, provider, run_tag, expected_rows),
            }

    result = {
        "schema": "certvic.v8.canonical_prediction_manifest.v1",
        "status": "blocked" if failures else "complete",
        "produced_model_results_by_this_script": False,
        "ingested_existing_kaggle_predictions": True,
        "paper_evidence": False,
        "failures": failures,
        "entries": manifest,
    }
    write_json(V8 / "canonical_prediction_manifest.json", result)
    write_json(V8 / "prediction_integrity_audit.json", result)
    _write_text(V8 / "canonical_prediction_manifest.md", _canonical_manifest_md(result))
    _write_text(V8 / "prediction_integrity_audit.md", _canonical_manifest_md(result))
    return result


def _canonical_manifest_md(result: dict) -> str:
    lines = [
        "# V8 Canonical Prediction Manifest",
        "",
        f"`status={result['status']}` `paper_evidence=false` `produced_model_results_by_this_script=false`",
        "",
        "| provider | run | rows | source | destination | status |",
        "| --- | --- | ---: | --- | --- | --- |",
    ]
    for key in sorted(result["entries"]):
        e = result["entries"][key]
        val = e.get("validation") or {}
        lines.append(
            f"| `{e['provider']}` | `{e['run_tag']}` | {val.get('n_rows', '')} | "
            f"`{e.get('source', '')}` | `{e['destination']}` | {e['status']} |"
        )
    if result["failures"]:
        lines += ["", "## Failures", ""]
        lines.extend(f"- {f}" for f in result["failures"])
    lines.append("")
    return "\n".join(lines)


def run_commands() -> list[dict]:
    commands: list[list[str]] = []
    for provider in PROVIDERS:
        commands.append([
            "python3", "scripts/pilot_report_from_raw.py",
            "--provider", provider,
            "--model-name", MODEL_NAMES[provider],
            "--run-label", provider,
            "--raw-spurious", str(RUNS["spurious"]["dest_dir"] / RUNS["spurious"]["filename"].format(provider=provider)),
            "--raw-perception-scaled", str(RUNS["perception_scaled"]["dest_dir"] / RUNS["perception_scaled"]["filename"].format(provider=provider)),
        ])
    commands += [
        [
            "python3", "-m", "certvic.validation.edit_detectability",
            "--tasks", "data/edits/spurious_flip_control/pilot_eval_tasks_reviewed.jsonl",
            "--out-dir", "data/results/spurious_flip_control/edit_detectability",
        ],
        ["python3", "-m", "certvic.v7.spurious_control_integration"],
        ["python3", "scripts/build_multimodel_summary.py"],
        ["python3", "scripts/build_main200_paper_tables.py"],
    ]
    logs: list[dict] = []
    for cmd in commands:
        proc = subprocess.run(cmd, cwd=REPO, text=True, capture_output=True, check=False)
        log = {
            "cmd": cmd,
            "returncode": proc.returncode,
            "stdout_tail": proc.stdout[-4000:],
            "stderr_tail": proc.stderr[-4000:],
        }
        logs.append(log)
        if proc.returncode != 0:
            write_json(REPORTS / "command_log.json", {"commands": logs})
            raise SystemExit(f"Command failed: {' '.join(cmd)}\n{proc.stderr[-1200:]}")
    write_json(REPORTS / "command_log.json", {"commands": logs})
    return logs


def _load_pilot_results() -> dict[str, dict]:
    out = {}
    for path in sorted(RESULTS.glob("pilot_report*/pilot_result.json")):
        data = _read_json(path)
        prov = data.get("provider")
        if prov:
            out[prov] = data
    return out


def build_spurious_report() -> dict:
    integration_path = RESULTS / "control_irrelevant_report/control_irrelevant_report.json"
    integration = _read_json(integration_path) if integration_path.exists() else {}
    pilot = _load_pilot_results()
    providers: dict[str, dict] = {}
    for provider in PROVIDERS:
        sp = (pilot.get(provider) or {}).get("spurious_flip_control") or (integration.get("metrics") or {}).get(provider) or {}
        providers[provider] = {
            "n_items": sp.get("n_items") or sp.get("n_scored"),
            "flipped": sp.get("flipped"),
            "spurious_flip_rate": sp.get("spurious_flip_rate"),
            "gate_threshold": sp.get("gate_threshold", SPURIOUS_THRESHOLD),
            "gate_pass": bool(sp.get("gate_pass")),
            "raw_prediction": _rel(RUNS["spurious"]["dest_dir"] / RUNS["spurious"]["filename"].format(provider=provider)),
        }
    all_pass = all(p["gate_pass"] for p in providers.values())
    status = "complete_pass" if all_pass else "blocked_failed_gate"
    detectability = _collect_detectability_status()
    result = {
        "schema": "certvic.v8.spurious_specificity_control_report.v1",
        "status": status,
        "evidence_status": "SPECIFICITY_CONTROL_PILOT_NON_EVIDENCE",
        "paper_evidence": False,
        "all_provider_gate_pass": all_pass,
        "providers": providers,
        "detectability_quality": detectability,
        "integration_status": {
            "path": _rel(integration_path),
            "status": integration.get("status"),
            "specificity_status": integration.get("specificity_status"),
            "gate_errors": integration.get("gate_errors", []),
        },
        "interpretation": "Specificity is not cleared unless every provider passes the configured spurious-flip gate.",
    }
    write_json(V8 / "spurious_specificity_control_report.json", result)
    write_json(V8 / "SPURIOUS_SPECIFICITY_CONTROL_REPORT.json", result)
    _write_text(V8 / "SPURIOUS_SPECIFICITY_CONTROL_REPORT.md", _spurious_md(result))
    return result


def _collect_detectability_status() -> dict:
    root = REPO / "data/results/spurious_flip_control/edit_detectability"
    files = sorted(root.rglob("*.json")) if root.exists() else []
    payloads = []
    for path in files:
        try:
            data = _read_json(path)
        except json.JSONDecodeError:
            continue
        payloads.append({"path": _rel(path), "keys": sorted(data.keys()), "data": data})
    return {
        "out_dir": _rel(root),
        "exists": root.exists(),
        "json_reports": payloads,
    }


def _spurious_md(result: dict) -> str:
    lines = [
        "# V8 Spurious Specificity Control Report",
        "",
        f"`status={result['status']}` `evidence_status={result['evidence_status']}` `paper_evidence=false`",
        "",
        "| provider | n | flipped | flip rate | threshold | gate |",
        "| --- | ---: | ---: | ---: | ---: | --- |",
    ]
    for provider in PROVIDERS:
        p = result["providers"][provider]
        lines.append(
            f"| `{provider}` | {p.get('n_items')} | {p.get('flipped')} | {p.get('spurious_flip_rate')} | "
            f"{p.get('gate_threshold')} | {'PASS' if p.get('gate_pass') else 'FAIL'} |"
        )
    lines += [
        "",
        f"Integration status: `{result['integration_status'].get('status')}` / `{result['integration_status'].get('specificity_status')}`.",
        "",
        "This control result does not create main-scale evidence. A failed provider keeps scaling and paper-grade claims blocked.",
        "",
    ]
    return "\n".join(lines)


def build_scaled_report() -> dict:
    pilot = _load_pilot_results()
    providers = {}
    for provider in PROVIDERS:
        psc = (pilot.get(provider) or {}).get("perception_control_scaled") or {}
        providers[provider] = {
            "n": psc.get("n"),
            "absent_accuracy": psc.get("absent_accuracy"),
            "absent": f"{psc.get('absent_correct')}/{psc.get('absent_n')}" if psc else None,
            "present_accuracy": psc.get("present_accuracy"),
            "present": f"{psc.get('present_correct')}/{psc.get('present_n')}" if psc else None,
            "overall_accuracy": psc.get("overall_accuracy"),
            "raw_prediction": _rel(RUNS["perception_scaled"]["dest_dir"] / RUNS["perception_scaled"]["filename"].format(provider=provider)),
        }
    complete = all(providers[p].get("n") == 369 for p in PROVIDERS)
    result = {
        "schema": "certvic.v8.scaled_perception_control_report.v1",
        "status": "complete" if complete else "blocked",
        "evidence_status": "HELDOUT_PERCEPTION_CONTROL_PILOT_NON_EVIDENCE",
        "paper_evidence": False,
        "providers": providers,
        "interpretation": "Held-out perception control; not main-scale intervention evidence.",
    }
    write_json(V8 / "scaled_perception_control_report.json", result)
    write_json(V8 / "SCALED_PERCEPTION_CONTROL_REPORT.json", result)
    _write_text(V8 / "SCALED_PERCEPTION_CONTROL_REPORT.md", _scaled_md(result))
    return result


def _scaled_md(result: dict) -> str:
    lines = [
        "# V8 Scaled Held-Out Perception Control Report",
        "",
        f"`status={result['status']}` `evidence_status={result['evidence_status']}` `paper_evidence=false`",
        "",
        "| provider | n | absent | present | overall accuracy |",
        "| --- | ---: | --- | --- | ---: |",
    ]
    for provider in PROVIDERS:
        p = result["providers"][provider]
        lines.append(
            f"| `{provider}` | {p.get('n')} | {p.get('absent')} ({p.get('absent_accuracy')}) | "
            f"{p.get('present')} ({p.get('present_accuracy')}) | {p.get('overall_accuracy')} |"
        )
    lines += ["", "This is a control run. It does not by itself clear the spurious specificity gate.", ""]
    return "\n".join(lines)


def build_v8_result_ledger(reports: dict) -> dict:
    entries = []
    for run_tag, cfg in RUNS.items():
        for provider in PROVIDERS:
            path = cfg["dest_dir"] / cfg["filename"].format(provider=provider)
            entries.append({
                "result_id": f"{provider}__{run_tag}",
                "provider": provider,
                "run_tag": run_tag,
                "artifact": _rel(path),
                "sha256": _sha256_file(path) if path.exists() else None,
                "n_rows": sum(1 for _ in path.open(encoding="utf-8")) if path.exists() else 0,
                "claim_level": "diagnostic_only" if run_tag in {"polarity", "mechanism"} else "pilot_control",
                "paper_evidence": False,
            })
    result = {
        "schema": "certvic.v8.result_ledger.v1",
        "status": "complete",
        "paper_evidence": False,
        "produced_model_results_by_this_script": False,
        "ingested_existing_kaggle_predictions": True,
        "reports": {k: _rel(v) for k, v in reports.items()},
        "entries": entries,
    }
    write_json(V8 / "v8_result_ledger.json", result)
    _write_text(V8 / "v8_result_ledger.md", _ledger_md(result))
    _write_csv(
        V8 / "v8_provider_run_matrix.csv",
        [
            {
                "provider": e["provider"],
                "run_tag": e["run_tag"],
                "n_rows": e["n_rows"],
                "paper_evidence": e["paper_evidence"],
                "artifact": e["artifact"],
            }
            for e in entries
        ],
        ["provider", "run_tag", "n_rows", "paper_evidence", "artifact"],
    )
    return result


def _ledger_md(result: dict) -> str:
    lines = [
        "# V8 Result Ledger",
        "",
        "`paper_evidence=false` `produced_model_results_by_this_script=false`",
        "",
        "| provider | run | rows | artifact | sha256 |",
        "| --- | --- | ---: | --- | --- |",
    ]
    for e in result["entries"]:
        lines.append(f"| `{e['provider']}` | `{e['run_tag']}` | {e['n_rows']} | `{e['artifact']}` | `{(e['sha256'] or '')[:16]}` |")
    lines.append("")
    return "\n".join(lines)


def build_summary_csvs(spurious: dict, scaled: dict, polarity: dict, mechanism: dict) -> None:
    pilot = _load_pilot_results()
    rows = []
    for provider in PROVIDERS:
        pr = pilot.get(provider, {})
        ps = (pr.get("presence_intervention") or {}).get("summary") or {}
        pc = (pr.get("presence_intervention") or {}).get("certification") or {}
        rows.append({
            "provider": provider,
            "presence_n": ps.get("n"),
            "presence_gap": ps.get("intervention_consistency_gap"),
            "cs_lower_bound": pc.get("lower_bound"),
            "presence_certified": pc.get("certified"),
            "spurious_flip_rate": spurious["providers"][provider].get("spurious_flip_rate"),
            "spurious_gate_pass": spurious["providers"][provider].get("gate_pass"),
            "scaled_perception_n": scaled["providers"][provider].get("n"),
        })
    _write_csv(V8 / "v8_multimodel_summary.csv", rows, list(rows[0]))

    control_rows = []
    for provider in PROVIDERS:
        control_rows.append({
            "provider": provider,
            "spurious_flip_rate": spurious["providers"][provider].get("spurious_flip_rate"),
            "spurious_gate_pass": spurious["providers"][provider].get("gate_pass"),
            "scaled_absent_accuracy": scaled["providers"][provider].get("absent_accuracy"),
            "scaled_present_accuracy": scaled["providers"][provider].get("present_accuracy"),
        })
    _write_csv(V8 / "v8_control_summary.csv", control_rows, list(control_rows[0]))


def _write_csv(path: Path, rows: list[dict], columns: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=columns)
        writer.writeheader()
        for row in rows:
            writer.writerow({c: "" if row.get(c) is None else row.get(c) for c in columns})


def build_evidence_policy_audit(spurious: dict, scaled: dict, polarity: dict, mechanism: dict) -> dict:
    result = {
        "schema": "certvic.v8.evidence_status_policy_audit.v1",
        "paper_evidence": False,
        "produced_model_results_by_this_script": False,
        "status": "blocked_for_scale" if not spurious["all_provider_gate_pass"] else "controls_complete_pilot_only",
        "gates": {
            "spurious_all_provider_gate_pass": spurious["all_provider_gate_pass"],
            "scaled_perception_complete": scaled["status"] == "complete",
            "polarity_complete": polarity["status"] == "complete",
            "mechanism_complete": mechanism["status"] == "complete",
            "two_rater_iaa_complete": False,
            "main500_executed": False,
        },
        "policy": "Pilot/control/diagnostic artifacts remain non-evidence until specificity, scale, and human-review gates are satisfied.",
    }
    write_json(V8 / "EVIDENCE_STATUS_POLICY_AUDIT.json", result)
    _write_text(
        V8 / "EVIDENCE_STATUS_POLICY_AUDIT.md",
        "\n".join([
            "# V8 Evidence Status Policy Audit",
            "",
            f"`status={result['status']}` `paper_evidence=false`",
            "",
            "| gate | value |",
            "| --- | --- |",
            *[f"| {k} | {v} |" for k, v in result["gates"].items()],
            "",
            result["policy"],
            "",
        ]),
    )
    return result


def build_failure_taxonomy_and_gallery(spurious: dict, polarity: dict, mechanism: dict) -> tuple[dict, dict]:
    tax = {
        "schema": "certvic.v8.failure_taxonomy.v1",
        "paper_evidence": False,
        "categories": [
            {
                "id": "spurious_specificity_gate_fail",
                "status": "observed" if not spurious["all_provider_gate_pass"] else "not_observed",
                "providers": [p for p, m in spurious["providers"].items() if not m.get("gate_pass")],
            },
            {
                "id": "polarity_parse_or_gold_mismatch",
                "status": "diagnostic",
                "note": "See POLARITY_ABLATION_REPORT for parse and row-accuracy distributions.",
            },
            {
                "id": "mechanism_context_or_residual_signal",
                "status": "diagnostic",
                "note": "See MECHANISM_PROBE_REPORT for probe-family distributions.",
            },
        ],
    }
    gallery_items = []
    for provider in PROVIDERS:
        sp_path = RUNS["spurious"]["dest_dir"] / RUNS["spurious"]["filename"].format(provider=provider)
        by_item: dict[str, dict] = defaultdict(dict)
        for row in _read_jsonl(sp_path):
            by_item[row["item_id"]][row["image_variant"]] = row
        for item_id, pair in sorted(by_item.items()):
            if pair.get("original", {}).get("parsed_answer") != pair.get("edited", {}).get("parsed_answer"):
                gallery_items.append({
                    "provider": provider,
                    "category": "spurious_flip",
                    "item_id": item_id,
                    "original_answer": pair.get("original", {}).get("parsed_answer"),
                    "edited_answer": pair.get("edited", {}).get("parsed_answer"),
                })
                if len([g for g in gallery_items if g["provider"] == provider and g["category"] == "spurious_flip"]) >= 3:
                    break
    gallery = {
        "schema": "certvic.v8.qualitative_gallery.v1",
        "paper_evidence": False,
        "status": "diagnostic_examples_only",
        "items": gallery_items,
        "note": "No human labels are inferred here; examples are selected from prediction disagreements only.",
    }
    write_json(V8 / "FAILURE_TAXONOMY_V8.json", tax)
    write_json(V8 / "QUALITATIVE_GALLERY_V8.json", gallery)
    _write_text(
        V8 / "FAILURE_TAXONOMY_V8.md",
        "# V8 Failure Taxonomy\n\n"
        + "\n".join(f"- `{c['id']}`: {c['status']}" for c in tax["categories"])
        + "\n",
    )
    _write_text(
        V8 / "QUALITATIVE_GALLERY_V8.md",
        "# V8 Qualitative Gallery\n\nDiagnostic examples only; no human labels are inferred.\n\n"
        + "\n".join(f"- `{i['provider']}` `{i['item_id']}` {i['original_answer']} -> {i['edited_answer']}" for i in gallery_items)
        + "\n",
    )
    return tax, gallery


def _relativize_maybe(path_value: str | None) -> str:
    if not path_value:
        return ""
    p = Path(path_value)
    if p.is_absolute():
        try:
            return p.relative_to(REPO).as_posix()
        except ValueError:
            return p.name
    return path_value


def build_human_exports() -> tuple[dict, dict]:
    reviewed_path = RESULTS / "pilot_eval_tasks_reviewed_v2.jsonl"
    reviewed = [r for r in read_jsonl(reviewed_path) if r.get("visual_review_status") == "approved"]

    residual_dir = REPO / "data/annotations/v8_residual_cue_audit"
    residual_dir.mkdir(parents=True, exist_ok=True)
    residual_sheet = residual_dir / "residual_cue_audit_sheet.csv"
    residual_cols = [
        "item_id", "edit_id", "original_image_path", "edited_image_path", "target_object", "edit_type",
        "residual_target_visible", "residual_type", "human_absence_confident", "notes", "reviewer_id",
    ]
    with residual_sheet.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=residual_cols)
        w.writeheader()
        for it in reviewed:
            w.writerow({
                "item_id": it.get("item_id"),
                "edit_id": it.get("edit_id"),
                "original_image_path": _relativize_maybe(it.get("original_image_path")),
                "edited_image_path": _relativize_maybe(it.get("edited_image_path")),
                "target_object": it.get("question_object"),
                "edit_type": it.get("edit_type"),
                "residual_target_visible": "",
                "residual_type": "",
                "human_absence_confident": "",
                "notes": "",
                "reviewer_id": "",
            })
    residual = {
        "schema": "certvic.v8.residual_cue_export.v1",
        "status": "review_pending",
        "paper_evidence": False,
        "n_items": len(reviewed),
        "sheet_path": _rel(residual_sheet),
        "human_fields_blank": True,
    }
    write_json(residual_dir / "residual_cue_audit_export.json", residual)
    _write_text(V8 / "RESIDUAL_CUE_AUDIT_EXPORT_REPORT.md", f"# V8 Residual Cue Audit Export\n\nReview pending. Sheet: `{_rel(residual_sheet)}`. Human fields are blank.\n")

    iaa_dir = REPO / "data/annotations/v8_second_rater_iaa"
    iaa_dir.mkdir(parents=True, exist_ok=True)
    iaa_sheet = iaa_dir / "second_rater_review_sheet.csv"
    iaa_cols = [
        "blind_order", "item_id", "edit_id", "target_object", "edit_type",
        "original_image_path", "edited_image_path", "question",
        "photorealism", "single_factor", "target_absent_after_edit", "answerability",
        "required_answer_change_unambiguous", "residual_target_cue_visible",
        "confidence", "keep_for_eval", "notes", "reviewer_id",
    ]
    with iaa_sheet.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=iaa_cols)
        w.writeheader()
        for idx, it in enumerate(sorted(reviewed, key=lambda r: r.get("item_id", "")), start=1):
            w.writerow({
                "blind_order": idx,
                "item_id": it.get("item_id"),
                "edit_id": it.get("edit_id"),
                "target_object": it.get("question_object"),
                "edit_type": it.get("edit_type"),
                "original_image_path": _relativize_maybe(it.get("original_image_path")),
                "edited_image_path": _relativize_maybe(it.get("edited_image_path")),
                "question": it.get("question_edited"),
                "photorealism": "",
                "single_factor": "",
                "target_absent_after_edit": "",
                "answerability": "",
                "required_answer_change_unambiguous": "",
                "residual_target_cue_visible": "",
                "confidence": "",
                "keep_for_eval": "",
                "notes": "",
                "reviewer_id": "",
            })
    iaa = {
        "schema": "certvic.v8.second_rater_iaa_export.v1",
        "status": "second_rater_pending",
        "paper_evidence": False,
        "n_items": len(reviewed),
        "sheet_path": _rel(iaa_sheet),
        "human_fields_blank": True,
        "blinded": True,
    }
    write_json(iaa_dir / "second_rater_iaa_status.json", iaa)
    _write_text(V8 / "SECOND_RATER_IAA_STATUS.md", f"# V8 Second-Rater IAA Status\n\nSecond rater pending. Sheet: `{_rel(iaa_sheet)}`. Human fields are blank.\n")
    write_json(V8 / "SECOND_RATER_IAA_STATUS.json", iaa)
    return residual, iaa


def build_statistical_and_scale_docs(spurious: dict) -> dict:
    plan_rows = [
        {"lane": "main500_planning", "status": "ready_plan", "estimated_runtime": "CPU 10-30 min"},
        {
            "lane": "main500_diffusion",
            "status": "blocked_until_spurious_gate_passes" if not spurious["all_provider_gate_pass"] else "ready_to_run",
            "estimated_runtime": "Kaggle T4x2 6-8 hr",
        },
        {"lane": "main500_quality_detectability", "status": "planned", "estimated_runtime": "CPU 15-60 min"},
        {"lane": "main500_human_review", "status": "planned", "estimated_runtime": "20-25 hr"},
        {"lane": "main500_vlm", "status": "planned", "estimated_runtime": "model dependent, estimate from measured per-generation rates"},
    ]
    _write_csv(V8 / "v8_power_plan.csv", plan_rows, ["lane", "status", "estimated_runtime"])
    result = {
        "schema": "certvic.v8.statistical_sensitivity.v1",
        "paper_evidence": False,
        "status": "planning_only",
        "main500_go": bool(spurious["all_provider_gate_pass"]),
        "note": "No new sequential claim is made by V8 ingestion. Main-500 remains blocked if specificity fails.",
        "power_plan_csv": _rel(V8 / "v8_power_plan.csv"),
    }
    write_json(V8 / "STATISTICAL_SENSITIVITY_V8.json", result)
    _write_text(
        V8 / "STATISTICAL_SENSITIVITY_V8.md",
        "# V8 Statistical Sensitivity and Sequential Validation\n\n"
        f"`main500_go={result['main500_go']}` `paper_evidence=false`\n\n"
        "The V8 builder records planning estimates only. It does not execute a new sequential test.\n",
    )
    go = {
        "schema": "certvic.v8.main500_go_nogo.v1",
        "go": bool(spurious["all_provider_gate_pass"]),
        "verdict": "GO_AFTER_CONTROL_PASS" if spurious["all_provider_gate_pass"] else "NO_GO_SPECIFICITY_GATE_FAILED",
        "paper_evidence": False,
        "blocking_reason": None if spurious["all_provider_gate_pass"] else "At least one provider failed the spurious-flip specificity gate.",
    }
    write_json(V8 / "MAIN500_GO_NOGO_PLAN.json", go)
    _write_text(
        V8 / "MAIN500_GO_NOGO_PLAN.md",
        "# V8 Main-500 GO/NO-GO Plan\n\n"
        f"Verdict: **{go['verdict']}**.\n\n"
        "Do not execute Main-500 GPU scale until the specificity gate is cleared without weakening thresholds.\n",
    )
    return result


def build_paper_artifacts(spurious: dict, scaled: dict, polarity: dict, mechanism: dict) -> dict:
    paper_sections = REPO / "paper/sections"
    paper_tables = REPO / "paper/tables"
    paper_figures = REPO / "paper/figures"
    paper_sections.mkdir(parents=True, exist_ok=True)
    paper_tables.mkdir(parents=True, exist_ok=True)
    paper_figures.mkdir(parents=True, exist_ok=True)

    _write_text(
        paper_sections / "v8_results_scaffold.tex",
        "% V8 pilot-only scaffold. Numbers live in generated tables, not prose.\n"
        "\\paragraph{V8 post-newruns status.}\n"
        "The remaining controls were ingested from external Kaggle artifacts and audited under the pilot evidence policy. "
        "The specificity gate remains the decision point for any scale claim.\n",
    )
    _write_text(
        paper_sections / "v8_limitations_scaffold.tex",
        "% V8 limitations scaffold.\n"
        "\\paragraph{Current limitations.}\n"
        "These artifacts remain pilot and diagnostic outputs. Main-scale execution, second-rater agreement, and any failed specificity gate must be resolved before stronger claims.\n",
    )
    _write_text(paper_tables / "v8_control_results.tex", _tex_control(spurious, scaled))
    _write_text(paper_tables / "v8_polarity_ablation.tex", _tex_polarity(polarity))
    _write_text(paper_tables / "v8_mechanism_probe_summary.tex", _tex_mechanism(mechanism))
    main_table_src = RESULTS / "tables/main200_multimodel_results.tex"
    if main_table_src.exists():
        shutil.copy2(main_table_src, paper_tables / "v8_main_pilot_results.tex")
    write_json(
        paper_figures / "v8_figure_manifest.json",
        {
            "schema": "certvic.v8.figure_manifest.v1",
            "paper_evidence": False,
            "figures": [],
            "note": "No new bitmap figure is generated by V8 ingestion. Use tables and diagnostic CSVs.",
        },
    )
    report = {
        "schema": "certvic.v8.paper_artifacts.v1",
        "paper_evidence": False,
        "files": [
            "paper/sections/v8_results_scaffold.tex",
            "paper/sections/v8_limitations_scaffold.tex",
            "paper/tables/v8_main_pilot_results.tex",
            "paper/tables/v8_control_results.tex",
            "paper/tables/v8_polarity_ablation.tex",
            "paper/tables/v8_mechanism_probe_summary.tex",
            "paper/figures/v8_figure_manifest.json",
        ],
    }
    _write_text(V8 / "PAPER_ARTIFACTS_V8.md", "# V8 Paper Artifacts\n\n" + "\n".join(f"- `{f}`" for f in report["files"]) + "\n")
    write_json(V8 / "PAPER_ARTIFACTS_V8.json", report)
    return report


def _tex_escape(text: str) -> str:
    return text.replace("_", r"\_")


def _tex_control(spurious: dict, scaled: dict) -> str:
    lines = [
        "% PILOT ONLY. Generated by scripts/build_v8_upgrade.py.",
        r"\begin{tabular}{lrrr}",
        r"\toprule",
        r"Provider & Spurious flip & Gate & Scaled perception \\",
        r"\midrule",
    ]
    for p in PROVIDERS:
        sp = spurious["providers"][p]
        sc = scaled["providers"][p]
        gate = "pass" if sp.get("gate_pass") else "fail"
        lines.append(f"{_tex_escape(p)} & {sp.get('spurious_flip_rate')} & {gate} & {sc.get('overall_accuracy')} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def _tex_polarity(polarity: dict) -> str:
    lines = [
        "% DIAGNOSTIC ONLY. Generated by scripts/build_v8_upgrade.py.",
        r"\begin{tabular}{llrr}",
        r"\toprule",
        r"Provider & Family & Parse rate & Row accuracy \\",
        r"\midrule",
    ]
    for p in PROVIDERS:
        for fam, vals in polarity["providers"][p]["families"].items():
            lines.append(f"{_tex_escape(p)} & {_tex_escape(fam)} & {vals.get('parse_rate')} & {vals.get('row_accuracy')} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def _tex_mechanism(mechanism: dict) -> str:
    lines = [
        "% DIAGNOSTIC ONLY. Generated by scripts/build_v8_upgrade.py.",
        r"\begin{tabular}{llrr}",
        r"\toprule",
        r"Provider & Family & Decision parse & Decision accuracy \\",
        r"\midrule",
    ]
    for p in PROVIDERS:
        for fam, vals in mechanism["providers"][p]["families"].items():
            lines.append(f"{_tex_escape(p)} & {_tex_escape(fam)} & {vals.get('decision_parse_rate')} & {vals.get('decision_accuracy')} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def build_reviewer_release_runbooks(spurious: dict) -> tuple[dict, dict]:
    reviewer = {
        "schema": "certvic.v8.reviewer_attack_harness.v1",
        "paper_evidence": False,
        "status": "blocked" if not spurious["all_provider_gate_pass"] else "pilot_controls_available",
        "top_blocker": None if spurious["all_provider_gate_pass"] else "spurious_specificity_gate_failed",
        "attacks": [
            {"id": "specificity", "status": "blocked" if not spurious["all_provider_gate_pass"] else "answered"},
            {"id": "scale", "status": "unanswered"},
            {"id": "human_iaa", "status": "unanswered"},
            {"id": "second_domain", "status": "unanswered"},
        ],
    }
    write_json(V8 / "REVIEWER_ATTACK_HARNESS_V8.json", reviewer)
    _write_text(V8 / "REVIEWER_ATTACK_HARNESS_V8.md", "# V8 Reviewer Attack Harness\n\nTop blocker: `" + str(reviewer["top_blocker"]) + "`.\n")

    release = {
        "schema": "certvic.v8.release_reproducibility_audit.v1",
        "paper_evidence": False,
        "status": "recipe_first_not_release_ready",
        "allow": ["scripts/build_v8_upgrade.py", "certvic/v8/*.py", "data/results/main_real_200/v8_upgrade/*.md"],
        "deny": ["model weights", "fake predictions", "human labels not actually collected", "private local paths"],
    }
    write_json(V8 / "RELEASE_REPRODUCIBILITY_AUDIT_V8.json", release)
    write_json(V8 / "v8_release_allow_deny_manifest.json", release)
    _write_text(V8 / "RELEASE_REPRODUCIBILITY_AUDIT_V8.md", "# V8 Release Reproducibility Audit\n\nRecipe-first status; no model weights are included.\n")
    return reviewer, release


def build_runbooks() -> None:
    runbook_dir = REPO / "docs/runbooks"
    runbook_dir.mkdir(parents=True, exist_ok=True)
    common = (
        "All V8 outputs are pilot or diagnostic only. Do not mark paper_evidence=true. "
        "Do not run paid APIs or paid cloud.\n"
    )
    _write_text(
        runbook_dir / "MAIN500_V8_DIFFUSION_RUNBOOK.md",
        "# Main-500 V8 Diffusion Runbook\n\n"
        + common
        + "\nRun only after the spurious specificity gate passes for every provider. Use the existing T4x2 diffusion template and keep output zips free of model weights.\n",
    )
    _write_text(
        runbook_dir / "HUMAN_REVIEW_RUNBOOK.md",
        "# V8 Human Review Runbook\n\n"
        + common
        + "\nUse `data/annotations/v8_residual_cue_audit/residual_cue_audit_sheet.csv` and `data/annotations/v8_second_rater_iaa/second_rater_review_sheet.csv`. Human fields must be completed by real reviewers only.\n",
    )
    _write_text(
        runbook_dir / "VLM_EVAL_RUNBOOK.md",
        "# V8 VLM Eval Runbook\n\n"
        + common
        + "\nUse the T4x2 notebooks under `notebooks/kaggle/` for any remaining GPU inference. Download prediction zips, place them under `kaggleoutputs/newruns`, then run `python3 scripts/build_v8_upgrade.py` locally.\n",
    )
    _write_text(
        runbook_dir / "LOCAL_INGEST_AUDIT_RUNBOOK.md",
        "# V8 Local Ingest and Audit Runbook\n\n"
        + common
        + "\n```bash\n"
        + "python3 scripts/build_v8_upgrade.py\n"
        + "python3 -m pytest -q tests/test_v8_upgrade.py\n"
        + "python3 -m pytest -q\n"
        + "python3 -m certvic.validation.claim_language_guard --root docs --out data/results/main_real_200/v8_upgrade/claim_guard_final.md\n"
        + "python3 -m certvic.security.release_privacy_audit --root . --out data/results/main_real_200/v8_upgrade/privacy_audit_final.md --json-out data/results/main_real_200/v8_upgrade/privacy_audit_final.json\n"
        + "```\n",
    )


def build_scorecard_and_handoff(spurious: dict, scaled: dict, polarity: dict, mechanism: dict) -> dict:
    scorecard = {
        "schema": "certvic.v8.cvpr_readiness_scorecard.v1",
        "paper_evidence": False,
        "ready": False,
        "blocking_conditions": [
            "spurious specificity gate failed" if not spurious["all_provider_gate_pass"] else None,
            "main500 not executed",
            "second-rater IAA not complete",
            "human residual-cue audit not complete",
        ],
        "completed_controls": {
            "scaled_perception": scaled["status"] == "complete",
            "polarity": polarity["status"] == "complete",
            "mechanism": mechanism["status"] == "complete",
        },
    }
    scorecard["blocking_conditions"] = [b for b in scorecard["blocking_conditions"] if b]
    write_json(V8 / "CVPR_READINESS_SCORECARD_V8.json", scorecard)
    _write_text(
        V8 / "CVPR_READINESS_SCORECARD_V8.md",
        "# V8 CVPR Readiness Scorecard\n\n"
        f"Ready: **{scorecard['ready']}**.\n\n"
        + "\n".join(f"- {b}" for b in scorecard["blocking_conditions"])
        + "\n",
    )
    handoff = {
        "schema": "certvic.v8.final_handoff.v1",
        "paper_evidence": False,
        "produced_model_results_by_this_script": False,
        "ingested_existing_kaggle_predictions": True,
        "cvpr_ready": scorecard["ready"],
        "spurious_control_ready": spurious["all_provider_gate_pass"],
        "remaining_to_run": [
            "resolve spurious specificity failure",
            "main500 diffusion and VLM scale",
            "main500 CPU detectability/quality",
            "human residual cue audit",
            "second-rater IAA",
        ],
    }
    write_json(V8 / "v8_final_handoff.json", handoff)
    _write_text(
        V8 / "V8_FINAL_HANDOFF.md",
        "# V8 Final Handoff\n\n"
        "`produced_model_results_by_this_script=false` `paper_evidence=false`\n\n"
        f"Spurious control ready: **{handoff['spurious_control_ready']}**.\n\n"
        "The V8 local builder ingested existing Kaggle prediction files and produced reports. It did not run GPU inference.\n",
    )
    return scorecard


def build_task_ledger(spurious: dict, scaled: dict, polarity: dict, mechanism: dict) -> dict:
    tasks = []
    names = [
        "orientation",
        "newruns_discovery_inventory",
        "prediction_integrity_normalization",
        "spurious_ingest_detectability",
        "spurious_control_integration",
        "scaled_perception_ingest",
        "polarity_ablation_analysis",
        "mechanism_probe_analysis",
        "evidence_status_policy_audit",
        "failure_taxonomy_gallery",
        "residual_cue_human_audit_export",
        "second_rater_iaa_export",
        "statistical_sensitivity_plan",
        "paper_tables_figures_scaffold",
        "reviewer_attack_harness",
        "release_privacy_reproducibility_audit",
        "main500_go_nogo",
        "main500_runbook_refresh",
        "cvpr_readiness_scorecard",
        "final_validation_handoff",
        "single_master_prompt_pack_complete",
        "local_tests_and_guards",
        "no_commit",
    ]
    for i, name in enumerate(names):
        status = "complete"
        if name in {"spurious_control_integration", "main500_go_nogo", "cvpr_readiness_scorecard"} and not spurious["all_provider_gate_pass"]:
            status = "blocked_by_failed_spurious_gate"
        tasks.append({"id": f"V8_{i:02d}", "name": name, "status": status, "paper_evidence": False})
    result = {
        "schema": "certvic.v8.task_ledger.v1",
        "paper_evidence": False,
        "tasks": tasks,
        "summary": {
            "spurious_all_provider_gate_pass": spurious["all_provider_gate_pass"],
            "scaled_status": scaled["status"],
            "polarity_status": polarity["status"],
            "mechanism_status": mechanism["status"],
        },
    }
    write_json(V8 / "v8_task_ledger.json", result)
    _write_text(
        V8 / "V8_TASK_LEDGER.md",
        "# V8 Task Ledger\n\n"
        + "\n".join(f"- `{t['id']}` {t['name']}: {t['status']}" for t in tasks)
        + "\n",
    )
    return result


def main() -> None:
    setup_dirs()
    write_contract()
    snapshot_pre_v8()
    inventory_newruns()
    manifest = normalize_predictions()
    if manifest["status"] != "complete":
        build_task_ledger(
            {"all_provider_gate_pass": False},
            {"status": "blocked"},
            {"status": "blocked"},
            {"status": "blocked"},
        )
        raise SystemExit("Prediction normalization blocked: " + "; ".join(manifest["failures"]))

    run_commands()
    spurious = build_spurious_report()
    scaled = build_scaled_report()
    polarity = build_polarity_report(RESULTS / "kaggle_polarity", V8)
    mechanism = build_mechanism_report(RESULTS / "kaggle_mechanism", V8)
    reports = {
        "spurious": V8 / "spurious_specificity_control_report.json",
        "scaled": V8 / "scaled_perception_control_report.json",
        "polarity": V8 / "polarity_ablation_report.json",
        "mechanism": V8 / "mechanism_probe_report.json",
    }
    build_v8_result_ledger(reports)
    build_summary_csvs(spurious, scaled, polarity, mechanism)
    build_evidence_policy_audit(spurious, scaled, polarity, mechanism)
    build_failure_taxonomy_and_gallery(spurious, polarity, mechanism)
    build_human_exports()
    build_statistical_and_scale_docs(spurious)
    build_paper_artifacts(spurious, scaled, polarity, mechanism)
    build_reviewer_release_runbooks(spurious)
    build_runbooks()
    build_scorecard_and_handoff(spurious, scaled, polarity, mechanism)
    build_task_ledger(spurious, scaled, polarity, mechanism)
    print(json.dumps({
        "status": "complete",
        "v8_dir": _rel(V8),
        "spurious_all_provider_gate_pass": spurious["all_provider_gate_pass"],
        "produced_model_results_by_this_script": False,
    }, sort_keys=True))


if __name__ == "__main__":
    main()
