#!/usr/bin/env bash
set -euo pipefail

# Stage 03: edit generation only after the dry-run is inspected.
# This may require a free GPU session, but it must not run VLM inference.
python3 -m certvic.data.select_pilot_items --sources data/results/tiny_real_pilot/ade20k_sources.jsonl --masks data/results/tiny_real_pilot/ade20k_masks.jsonl --out data/results/tiny_real_pilot/pilot_selection.jsonl --target 20 --seed 0 --min-mask-area-fraction 0.01 --max-mask-area-fraction 0.40 --summary-out data/results/tiny_real_pilot/pilot_selection_summary.json --label-policy configs/ade20k_label_policy.yaml --allowed-task-families support_stability occlusion_safety affordance_reachability control_irrelevant --domains household --splits train val --allow-partial
python3 -m certvic.edit.plan_edits --selection data/results/tiny_real_pilot/pilot_selection.jsonl --out data/results/tiny_real_pilot/pilot_edit_plan.jsonl --summary-out data/results/tiny_real_pilot/pilot_edit_plan_summary.json --rejected-out data/results/tiny_real_pilot/pilot_edit_plan_rejected.jsonl --seed 0 --label-policy configs/ade20k_label_policy.yaml
python3 -m certvic.data.preview_tasks --edit-plan data/results/tiny_real_pilot/pilot_edit_plan.jsonl --out data/results/tiny_real_pilot/pilot_task_preview.jsonl --summary-out data/results/tiny_real_pilot/pilot_task_preview_summary.json
python3 -m certvic.reporting.pilot_plan_report --selection data/results/tiny_real_pilot/pilot_selection.jsonl --edit-plan data/results/tiny_real_pilot/pilot_edit_plan.jsonl --task-preview data/results/tiny_real_pilot/pilot_task_preview.jsonl --out-dir data/results/tiny_real_pilot/pilot_plan_report
python3 -m certvic.edit.job_queue build --edit-plan data/results/tiny_real_pilot/pilot_edit_plan.jsonl --out data/results/tiny_real_pilot/diffusion_job_queue.jsonl --shards 2
python3 -m certvic.edit.engines --edit-plan data/results/tiny_real_pilot/pilot_edit_plan.jsonl --out-dir data/edits/tiny_real_pilot --out-manifest data/results/tiny_real_pilot/pilot_generated_edits.jsonl --rejected-out data/results/tiny_real_pilot/pilot_generated_rejected.jsonl --summary-out data/results/tiny_real_pilot/pilot_generation_summary.json --engine diffusers_inpaint_optional --max-items 20 --seed 0 --resume --fail-fast
python3 -m certvic.edit.quality_report --generated-manifest data/results/tiny_real_pilot/pilot_generated_edits.jsonl --rejected data/results/tiny_real_pilot/pilot_generated_rejected.jsonl --out-dir data/results/tiny_real_pilot/tiny_edit_quality_report
python3 -m certvic.data.materialize_tasks --task-preview data/results/tiny_real_pilot/pilot_task_preview.jsonl --generated-edits data/results/tiny_real_pilot/pilot_generated_edits.jsonl --out data/results/tiny_real_pilot/pilot_eval_tasks_tiny.jsonl --summary-out data/results/tiny_real_pilot/pilot_eval_tasks_tiny_summary.json
python3 -m certvic.validation.export_visual_review --tasks data/results/tiny_real_pilot/pilot_eval_tasks_tiny.jsonl --generated-edits data/results/tiny_real_pilot/pilot_generated_edits.jsonl --out data/results/tiny_real_pilot/visual_review_sheet.csv --max-items 20 --seed 0
